### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by LukeWheeldon** [stakelink/substrate-payctl#1]
Thank you for this very handy project. I find myself unable to install it unfortunately. OS is Debian 10.

```
$ git clone http://github.com/stakelink/substrate-payctl
Cloning into 'substrate-payctl'...
warning: redirecting to https://github.com/stakelink/substrate-payctl/
remote: Enumerating objects: 16, done.
remote: Counting objects: 100% (16/16), done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 16 (delta 1), reused 16 (delta 1), pack-reused 0
Unpacking objects: 100% (16/16), done.

$ pip install substrate-payctl
Collecting substrate-payctl
Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://pypi.org/simple/substrate-payctl/
```

Update:

The following command seems to do the trick:
```
python3 -m pip install -e git+https://github.com/stakelink/substrate-payctl#egg=payctl
```

However I then get the following error:
```
requests 2.25.1 has requirement idna<3,>=2.5, but you'll have idna 3.1 which is incompatible.
```

Which seems to be fixed that way:
```
python3 -m pip uninstall idna
python3 -m pip install idna==2.10
```

**Comment by apuigsech** [comment]
_pip install_ command is ambiguous and its parameter may mean a public python package or a local folder. I think in your case is taking the first option, and the public package don't exist.

I think it should work if you add a "/" at the end to explicitly indicate it is a folder:

```
pip install substrate-payctl/
```

Another option is the following:

```
cd substrate-payctl
pip install .
```

**Comment by iicc1** [comment]
`pip3 install substrate-payctl/` worked for me, thanks.
 
After that, when I execute `payctl` it says `Command 'payctl' not found`. 
What do we need to do in order to launch the executable?
Thanks

**Comment by LukeWheeldon** [comment]
@iicc1 you need to add the path of payctl to your environment variables, such as, for example:

```
echo "export PATH=$HOME/.local/bin:$PATH" >> ~/.bashrc
source .bashrc
```

The method can vary slightly depending on your system.
