### ISSUE TITLE
Cannot query / pay more than one stash account

### ISSUE THREAD

**Issue by TheGoldenEye** [stakelink/substrate-payctl#13]
it seems that multiple stash accounts cannot be queried
it does not matter if the accounts are passed via command line or config
it looks like only the data of the first account passed is correct, all further accounts take over the status of the first one 

Example: 
GxxV8DAcHCSzBbspu83AK9UoTYxzSQ6VVfdopjnkXfPtE8d has unclaimed eras 2320, 2319 and 2318
FiNuPk2iPirbKC7Spse3NuE9rWjzaQonZmk6wRvk1LcEU13 has no unclaimed eras

```
payctl -c ./default.conf list  GxxV8DAcHCSzBbspu83AK9UoTYxzSQ6VVfdopjnkXfPtE8d FiNuPk2iPirbKC7Spse3NuE9rWjzaQonZmk6wRvk1LcEU13

Era: 2321
	 GxxV8DAcHCSzBbspu83AK9UoTYxzSQ6VVfdopjnkXfPtE8d => 1.255767075386 KSM (claimed)
	 FiNuPk2iPirbKC7Spse3NuE9rWjzaQonZmk6wRvk1LcEU13 => 0.209294512564 KSM (claimed)
Era: 2320
	 GxxV8DAcHCSzBbspu83AK9UoTYxzSQ6VVfdopjnkXfPtE8d => 0.262080569196 KSM (unclaimed)
	 FiNuPk2iPirbKC7Spse3NuE9rWjzaQonZmk6wRvk1LcEU13 => 0.157248341517 KSM (unclaimed)
Era: 2319
	 GxxV8DAcHCSzBbspu83AK9UoTYxzSQ6VVfdopjnkXfPtE8d => 1.820096634906 KSM (unclaimed)
	 FiNuPk2iPirbKC7Spse3NuE9rWjzaQonZmk6wRvk1LcEU13 => 0.695919301582 KSM (unclaimed)
Era: 2318
	 GxxV8DAcHCSzBbspu83AK9UoTYxzSQ6VVfdopjnkXfPtE8d => 0.810994411792 KSM (unclaimed)
	 FiNuPk2iPirbKC7Spse3NuE9rWjzaQonZmk6wRvk1LcEU13 => 1.459789941226 KSM (unclaimed)
```

```
payctl -c ./default.conf list FiNuPk2iPirbKC7Spse3NuE9rWjzaQonZmk6wRvk1LcEU13 GxxV8DAcHCSzBbspu83AK9UoTYxzSQ6VVfdopjnkXfPtE8d

Era: 2321
	 FiNuPk2iPirbKC7Spse3NuE9rWjzaQonZmk6wRvk1LcEU13 => 0.209294512564 KSM (claimed)
	 GxxV8DAcHCSzBbspu83AK9UoTYxzSQ6VVfdopjnkXfPtE8d => 1.255767075386 KSM (claimed)
Era: 2320
	 FiNuPk2iPirbKC7Spse3NuE9rWjzaQonZmk6wRvk1LcEU13 => 0.157248341517 KSM (claimed)
	 GxxV8DAcHCSzBbspu83AK9UoTYxzSQ6VVfdopjnkXfPtE8d => 0.262080569196 KSM (claimed)
Era: 2319
	 FiNuPk2iPirbKC7Spse3NuE9rWjzaQonZmk6wRvk1LcEU13 => 0.695919301582 KSM (claimed)
	 GxxV8DAcHCSzBbspu83AK9UoTYxzSQ6VVfdopjnkXfPtE8d => 1.820096634906 KSM (claimed)
Era: 2318
	 FiNuPk2iPirbKC7Spse3NuE9rWjzaQonZmk6wRvk1LcEU13 => 1.459789941226 KSM (claimed)
	 GxxV8DAcHCSzBbspu83AK9UoTYxzSQ6VVfdopjnkXfPtE8d => 0.810994411792 KSM (claimed)

```

**Comment by apuigsech** [comment]
Thanks for reporting.

We are currently working on the version 2, which will make easy to operate more than one validator (even on different networks). It will probably take a couple of weeks from now to be released.

**Comment by TheGoldenEye** [comment]
ok, thx for information

**Comment by apuigsech** [comment]
I have just pushed an initial refactor for the version 2. You can get it from the brach 'v2' and it would be very useful for us that you test it on your use case.

**Comment by TheGoldenEye** [comment]
Ok, I did the first tests:
1. payout for different accounts seems to work in principle
2. the values shown in list mode do not match the real rewards
3. it seems that just executed payouts are not recognized
example: extrinsics 7816008-2 and 7815962-3 in kusama

**Comment by apuigsech** [comment]
Thanks.

1. :-)

2. I need to investigate a bit on this one.

3. I know why this happened. I am using a cache system (and I enabled storage cache during my testing). So It identified some pending payouts on the cache data that were already done; _AlreadyClaimed_. You can fix this by removing line 82 on utils.py.

**Comment by apuigsech** [comment]
Regarding point (2) can you gimme examples of rewards not matching reality. My observation is that it's doing it good, taking into account that it's showing the whole rewards from the validator (the sum of the rewards to all nominators).

**Comment by TheGoldenEye** [comment]
You're right, of course, I hadn't thought of that.
Then the values will certainly be correct.
