### ISSUE TITLE
Payctl not paying the validator unclaimed eras

### ISSUE THREAD

**Issue by iicc1** [stakelink/substrate-payctl#5]
Hello,
I'm trying to pay my Kusama validator unclaimed eras but Payctl is not paying these unpaid eras. I'm not sure what I am doing wrong.

This is the process I follow:

First, I list the pending eras
```
payctl -c kusama_payouts.conf list
Era: 2080
         EfcQCKZJaNu2vcrpnJDCoh1ub4mGWcHVzeU8ghUH7Co9rui => 0.4740286049049683 KSM  (claimed)
Era: 2081
         EfcQCKZJaNu2vcrpnJDCoh1ub4mGWcHVzeU8ghUH7Co9rui => 0.6279231647160968 KSM  (claimed)
Era: 2082
         EfcQCKZJaNu2vcrpnJDCoh1ub4mGWcHVzeU8ghUH7Co9rui => 0.3152656992124602 KSM  (unclaimed)
Era: 2083
         EfcQCKZJaNu2vcrpnJDCoh1ub4mGWcHVzeU8ghUH7Co9rui => 1.266213699415513 KSM  (unclaimed)
Era: 2084
         EfcQCKZJaNu2vcrpnJDCoh1ub4mGWcHVzeU8ghUH7Co9rui => 0.3162418574586292 KSM  (unclaimed)
Era: 2085
         EfcQCKZJaNu2vcrpnJDCoh1ub4mGWcHVzeU8ghUH7Co9rui => 1.1052962591744913 KSM  (unclaimed)
Era: 2078
         EfcQCKZJaNu2vcrpnJDCoh1ub4mGWcHVzeU8ghUH7Co9rui => 1.2636588428250672 KSM  (claimed)
Era: 2079
         EfcQCKZJaNu2vcrpnJDCoh1ub4mGWcHVzeU8ghUH7Co9rui => 1.1055529814017033 KSM  (claimed)
```

Then, I try to pay
```
payctl -c kusama_payouts.conf pay
```
But it does not return any message. If I check the pending eras again, I get the exact same result as before.

This is my payctl configuration
```
[Defaults]
RPCURL = wss://kusama-rpc.polkadot.io/
Network = kusama
DepthEras = 10
MinEras = 5
SigningAccount=xxxxxx
SigningMnemonic=x x x x x x x x x x x x

[EfcQCKZJaNu2vcrpnJDCoh1ub4mGWcHVzeU8ghUH7Co9rui]
```
I have a "payouts" account that has a stash nominating my validator, with enough funds to perform payments.

I'm using the latest code available (commit 693aefc)

Any help would be appreciated.

**Comment by apuigsech** [comment]
Your MinEras is at 5, which means it will only pay of there are 5 or more eras pending to pay. In your output there are only 4.

**Comment by iicc1** [comment]
> 
> 
> Your MinEras is at 5, which means it will only pay if there are 5 or more eras pending to pay. In your output there are only 4.
> 
> Change it to 1 or 0, if you want to pay always.

Oh I didn't know that, it works fine now. Thanks for the tip.
