### ISSUE TITLE
Rewards not correctly calculated on Kusama and Westend

### ISSUE THREAD

**Issue by mario-purestake** [stakelink/substrate-payctl#9]
I wanted to use this tool to list and claim the rewards for Polkadot and Kusama validators. I haven't gone for the claiming yet, but I saw that the amount shown on the list for an account doesn't match with Subscan on Kusama. For Polkadot was correct, so in order to check whether the problem was Kusama itself, I tried on Westend. The amounts are also different from what I see on Subscan.

### Kusama

Looks like it's deviated from the original around x10, but it's not exact.

[Subscan: Account CaRYnYy5JVW248MhNXxLb9NDaX7BWNE32vJfJKtQYY2bnqc](https://kusama.subscan.io/validator/CaRYnYy5JVW248MhNXxLb9NDaX7BWNE32vJfJKtQYY2bnqc?tab=reward)

![image](https://user-images.githubusercontent.com/66425016/119174648-2335e880-ba69-11eb-8527-e02c025db5fd.png)

 ```shell
Era: 2272
	 CaRYnYy5JVW248MhNXxLb9NDaX7BWNE32vJfJKtQYY2bnqc => 1.527830818531 KSM (claimed)
Era: 2273
	 CaRYnYy5JVW248MhNXxLb9NDaX7BWNE32vJfJKtQYY2bnqc => 0.728181107033 KSM (claimed)
Era: 2274
	 CaRYnYy5JVW248MhNXxLb9NDaX7BWNE32vJfJKtQYY2bnqc => 0.474321320758 KSM (unclaimed)
Era: 2275
	 CaRYnYy5JVW248MhNXxLb9NDaX7BWNE32vJfJKtQYY2bnqc => 1.558107418220 KSM (unclaimed)
Era: 2276
	 CaRYnYy5JVW248MhNXxLb9NDaX7BWNE32vJfJKtQYY2bnqc => 2.302051627331 KSM (unclaimed)
Era: 2265
	 CaRYnYy5JVW248MhNXxLb9NDaX7BWNE32vJfJKtQYY2bnqc => 0.359686077396 KSM (claimed)
Era: 2266
	 CaRYnYy5JVW248MhNXxLb9NDaX7BWNE32vJfJKtQYY2bnqc => 2.048714839176 KSM (claimed)
Era: 2267
	 CaRYnYy5JVW248MhNXxLb9NDaX7BWNE32vJfJKtQYY2bnqc => 0.120890854602 KSM (claimed)
Era: 2268
	 CaRYnYy5JVW248MhNXxLb9NDaX7BWNE32vJfJKtQYY2bnqc => 1.304925956364 KSM (claimed)
Era: 2269
	 CaRYnYy5JVW248MhNXxLb9NDaX7BWNE32vJfJKtQYY2bnqc => 1.775703157528 KSM (claimed)
```

### Westend

This one is deviated around +1 from original, but again, not exactly that amount.

[Subscan: Account 5CFPcUJgYgWryPaV1aYjSbTpbTLu42V32Ytw1L9rfoMAsfGh](https://westend.subscan.io/account/5CFPcUJgYgWryPaV1aYjSbTpbTLu42V32Ytw1L9rfoMAsfGh?tab=reward)

![image](https://user-images.githubusercontent.com/66425016/119174593-0ef1eb80-ba69-11eb-9a44-c32c5236ca7f.png)

```shell
Era: 3695
	 5CFPcUJgYgWryPaV1aYjSbTpbTLu42V32Ytw1L9rfoMAsfGh => 5.844152045836 WND (claimed)
Era: 3696
	 5CFPcUJgYgWryPaV1aYjSbTpbTLu42V32Ytw1L9rfoMAsfGh => 5.903647559308 WND (unclaimed)
Era: 3697
	 5CFPcUJgYgWryPaV1aYjSbTpbTLu42V32Ytw1L9rfoMAsfGh => 5.885072127001 WND (claimed)
Era: 3698
	 5CFPcUJgYgWryPaV1aYjSbTpbTLu42V32Ytw1L9rfoMAsfGh => 5.861527920418 WND (claimed)
Era: 3699
	 5CFPcUJgYgWryPaV1aYjSbTpbTLu42V32Ytw1L9rfoMAsfGh => 5.979938768956 WND (claimed)
Era: 3700
	 5CFPcUJgYgWryPaV1aYjSbTpbTLu42V32Ytw1L9rfoMAsfGh => 5.968844446703 WND (claimed)
Era: 3701
	 5CFPcUJgYgWryPaV1aYjSbTpbTLu42V32Ytw1L9rfoMAsfGh => 5.934309005170 WND (claimed)
Era: 3702
	 5CFPcUJgYgWryPaV1aYjSbTpbTLu42V32Ytw1L9rfoMAsfGh => 5.886596292480 WND (claimed)
Era: 3703
	 5CFPcUJgYgWryPaV1aYjSbTpbTLu42V32Ytw1L9rfoMAsfGh => 5.829322457762 WND (claimed)
Era: 3704
	 5CFPcUJgYgWryPaV1aYjSbTpbTLu42V32Ytw1L9rfoMAsfGh => 5.865111294876 WND (claimed)
```

What is weird for me is that the Polkadot is showing the correct values. Any clue on what could be the problem?

Thanks in advance

**Comment by apuigsech** [comment]
I think the problem is  related to the number of decimals. Each network uses a different number, and I am assuming the same for all.

Thanks for reporting! I'll work on fixing it.

**Comment by mario-purestake** [comment]
Thanks! Actually I made some local changes that I could push here as a PR because some of the types returned by the `substrateinterface` have changed over time. They're mainly for the `list` command, but I'll also check the `pay` in order to make it work. I'll make it either during the weekend or on Monday :grin:

**Comment by mario-purestake** [comment]
Hi @apuigsech, I tracked this down to the PolkadotJS Apps and it ended up being a bug on the runtime itself, and not with this library. The issue is below in case you want to take a look. Thanks for this tool btw, it feels good to work with something different than JS/TS when interacting with Polkadot :)

https://github.com/polkadot-js/apps/issues/5359
